version: '3'
networks:
  app-tier:
    driver: bridge
volumes:
  PROD_APP_TES_PLACE_REPLACE_ME__DB_BACKUP:
services:
  PROD_APP_TES_PLACE_REPLACE_ME__SERVICE_DB:
    container_name: PROD_APP_TES_PLACE_REPLACE_ME__SERVICE_DB_POSTGRES
    image: postgres:11
    restart: always
    env_file:
      - ../.env
    ports:
      - ${DB_DATABASE_PORT}:5432
    volumes:
      - PROD_APP_TES_PLACE_REPLACE_ME__DB_BACKUP:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - app-tier
  adminer:
    container_name: PROD_APP_TES_PLACE_REPLACE_ME__SERVICE_DB_ADMINER
    image: adminer
    restart: always
    depends_on:
      - PROD_APP_TES_PLACE_REPLACE_ME__SERVICE_DB
    env_file:
      - ../.env
    ports:
      - ${DB_ADMINER_PORT}:8080
    networks:
      - app-tier
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - PROD_APP_TES_PLACE_REPLACE_ME__SERVICE_DB
    env_file:
      - ../.env
    ports:
      - ${DB_PHP_MYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1